# Generated by Django 3.1.3 on 2020-11-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Ingrese el nombre de la licencia', max_length=20)),
                ('precio', models.FloatField(help_text='Precio de la licencia')),
            ],
        ),
        migrations.CreateModel(
            name='MIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Ingrese el modelo de la MIC', max_length=20)),
                ('zocalos', models.IntegerField(help_text='Numero de zocalos para opticas')),
                ('precio', models.FloatField(help_text='Precio de la tarjeta MIC')),
            ],
        ),
        migrations.CreateModel(
            name='RE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Ingrese el modelo de la RE', max_length=20)),
                ('precio', models.FloatField(help_text='Precio de la RE')),
            ],
        ),
        migrations.CreateModel(
            name='SCB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Ingrese el modelo de la SCB', max_length=20)),
                ('capacidad', models.IntegerField(help_text='Capacidad en Gbps/slot')),
                ('precio', models.FloatField(help_text='Precio de la tarjeta SCB')),
            ],
        ),
        migrations.CreateModel(
            name='MPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Ingrese el modelo de la MPC', max_length=20)),
                ('capacidad', models.IntegerField(help_text='Capacidad en Gbps/slot')),
                ('mics', models.BooleanField(default=True, help_text='Acepta MICs')),
                ('precio', models.FloatField(help_text='Precio de la tarjeta MPC')),
                ('licencias', models.ManyToManyField(help_text='Seleccione las posibles licencias', to='mxquote.Licencias')),
            ],
        ),
    ]
