# Generated by Django 3.1.3 on 2020-11-06 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mxquote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licencias',
            old_name='modelo',
            new_name='modelo_licencia',
        ),
        migrations.RenameField(
            model_name='licencias',
            old_name='precio',
            new_name='precio_licencia',
        ),
        migrations.RenameField(
            model_name='mic',
            old_name='modelo',
            new_name='modelo_mic',
        ),
        migrations.RenameField(
            model_name='mic',
            old_name='precio',
            new_name='precio_mic',
        ),
        migrations.RenameField(
            model_name='mpc',
            old_name='capacidad',
            new_name='capacidad_mpc',
        ),
        migrations.RenameField(
            model_name='mpc',
            old_name='licencias',
            new_name='licencias_mpc',
        ),
        migrations.RenameField(
            model_name='mpc',
            old_name='modelo',
            new_name='modelo_mpc',
        ),
        migrations.RenameField(
            model_name='mpc',
            old_name='precio',
            new_name='precio_mpc',
        ),
        migrations.RenameField(
            model_name='re',
            old_name='modelo',
            new_name='modelo_re',
        ),
        migrations.RenameField(
            model_name='re',
            old_name='precio',
            new_name='precio_re',
        ),
        migrations.RenameField(
            model_name='scb',
            old_name='capacidad',
            new_name='capacidad_scb',
        ),
        migrations.RenameField(
            model_name='scb',
            old_name='modelo',
            new_name='modelo_scb',
        ),
        migrations.RenameField(
            model_name='scb',
            old_name='precio',
            new_name='precio_scb',
        ),
    ]
