# Generated by Django 3.1.3 on 2020-11-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxquote', '0002_auto_20201106_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencias',
            name='precio_licencia',
            field=models.FloatField(help_text='Precio de la licencia en Euros'),
        ),
        migrations.AlterField(
            model_name='mic',
            name='precio_mic',
            field=models.FloatField(help_text='Precio de la tarjeta MIC en Euros'),
        ),
        migrations.AlterField(
            model_name='mpc',
            name='capacidad_mpc',
            field=models.IntegerField(help_text='Capacidad en Gbps'),
        ),
        migrations.AlterField(
            model_name='mpc',
            name='licencias_mpc',
            field=models.ManyToManyField(help_text='Seleccione las posibles licencias', null=True, to='mxquote.Licencias'),
        ),
        migrations.AlterField(
            model_name='mpc',
            name='precio_mpc',
            field=models.FloatField(help_text='Precio de la tarjeta MPC en Euros'),
        ),
        migrations.AlterField(
            model_name='re',
            name='precio_re',
            field=models.FloatField(help_text='Precio de la RE en Euros'),
        ),
        migrations.AlterField(
            model_name='scb',
            name='precio_scb',
            field=models.FloatField(help_text='Precio de la tarjeta SCB en Euros'),
        ),
    ]
