# Generated by Django 3.1.3 on 2020-11-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxquote', '0004_auto_20201106_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Ingrese el modelo de la Optica', max_length=20)),
                ('bandwidth', models.IntegerField(help_text='Ingrese el ancho de banda de la Optica en Gbps')),
                ('precio_optic', models.FloatField(help_text='Precio de la Optica')),
            ],
        ),
    ]
