# Generated by Django 3.1.3 on 2020-11-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mxquote', '0005_optics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licencias',
            old_name='modelo_licencia',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='licencias',
            old_name='precio_licencia',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='mic',
            old_name='modelo_mic',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='mic',
            old_name='precio_mic',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='mpc',
            old_name='capacidad_mpc',
            new_name='capacidad',
        ),
        migrations.RenameField(
            model_name='mpc',
            old_name='licencias_mpc',
            new_name='licencias',
        ),
        migrations.RenameField(
            model_name='mpc',
            old_name='modelo_mpc',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='mpc',
            old_name='precio_mpc',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='optics',
            old_name='precio_optic',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='re',
            old_name='modelo_re',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='re',
            old_name='precio_re',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='scb',
            old_name='capacidad_scb',
            new_name='capacidad',
        ),
        migrations.RenameField(
            model_name='scb',
            old_name='modelo_scb',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='scb',
            old_name='precio_scb',
            new_name='precio',
        ),
    ]
