# Generated by Django 3.1.3 on 2020-11-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxquote', '0006_auto_20201107_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='showmpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'default',
            },
        ),
    ]
