# Generated by Django 3.1.3 on 2020-11-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxquote', '0007_showmpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='showscb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scb', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelTable(
            name='showmpc',
            table=None,
        ),
    ]
