# Generated by Django 3.1.3 on 2020-11-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxquote', '0008_auto_20201108_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='showre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re', models.CharField(max_length=100)),
            ],
        ),
    ]
