# Generated by Django 3.1.3 on 2020-11-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxquote', '0009_showre'),
    ]

    operations = [
        migrations.CreateModel(
            name='showmic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mic', models.CharField(max_length=100)),
            ],
        ),
    ]
